### ISSUE TITLE
Gumbel copula and Gumbel distribution have the same name and collide 

### ISSUE THREAD

**Issue by jp5000** [hplgit/chaospy#8]
Hello Chaospy team. Great work with this library. 

Gumbel copula and Gumbel distribution have the same name and collide:

>>> dist_Q = cp.Gumbel(dist, theta=2.)

TypeError: Gumbel() got an unexpected keyword argument 'theta'

>>> cp.Gumbel?

cp.Gumbel(scale=1, loc=0)

>>> dist_Q = cp.Copula(dist, cp.gumbel(len(dist), theta=2.) ) 

works!!

**Comment by jonathf** [comment]
Thank you. :)

You're right. Both the Gumbel distribution and the Gumbel copula was on the same namespace, making a conflict.

I've renamed the distribution to Logweibull (which is equivalent).
