### ISSUE TITLE
Name `pcd` is not defined.

### ISSUE THREAD

**Issue by tsbertalan** [hplgit/chaospy#9]
The (docstring) examples for `cp.orth_svd`, `cp.orth_pcd`, and `cp.orth_hybrid` don't work for me.

    In [1]: import chaospy as cp
    In [2]: Z = cp.Normal()
    In [3]: print cp.orth_pcd(2, Z)
    ---------------------------------------------------------------------------
    NameError                                 Traceback (most recent call last)
    <ipython-input-3-078656d1e4da> in <module>()
    ----> 1 print cp.orth_pcd(2, Z)
    /usr/local/lib/python2.7/dist-packages/chaospy/orthogonal.pyc in orth_pcd(order, dist, eps, normed,     **kws)
        343     N = len(basis)
        344 
    --> 345     L, P = pcd(C, approx=1, pivot=1, tol=eps)
        346     Li = np.dot(P, np.linalg.inv(L.T))
        347 
    NameError: global name 'pcd' is not defined

Are these deprecated? From what package did that `pcd` use to come?

Additionally, the example for `orth_hybrid` refers to `orth_chol` instead.

**Comment by jonathf** [comment]
Yes, those three are all deprecated. I've updated the three methods to give deprecation warnings.

The PCD method is taken from a open source project called pymmf written by Michael Forbes. I specifically use the method based on the paper:
``What to do When Your Hessian is Not Invertable: Alternatives to
Model Respecification in Nonlinear Estimation,''
J. Gill and G. King
Socialogical Methods and Research, Vol. 32, No. 1 (2004):54--87

As for use of PCD in polynomial chaos expansions, it isn't yet. We are currently working through a second revision of a paper that uses the method to solve a specific task. Hopefully it will be published during the spring.
